name: Lint

on: [push, pull_request]

env:
  PIP_ROOT_USER_ACTION: "ignore"

jobs:
  lint:
    name: Lint Python code
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install pip
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip

    - name: Upgrade pip
      run: |
        python3 -m pip install --upgrade pip
        pip --version

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run flake8
      run: |
        flake8 .
